function Get-ManagerResponse {
    [CmdletBinding()]
$bws = @("Synergy",
"warm handoff",
"Have you asked the cloud team?",
"Can you look into that?",
"Think outside the box",
"Take it offline",
"Circle back",
"Low-hanging fruit",
"We need that by EOBD",
"cloud",
"cloud first",
"cloud strategery",
"To not know what you don’t know",
"It's not what you know, its who you know",
"We got to get moving on this!",
"Big Data",
"Big Beautiful Data",
"Move the needle",
"Leverage",
"Agile",
"Best Practice",
"Digital transformation",
"Deep dive",
"Bandwidth",
"Customer journey",
"Moving forward",
"Next level",
"Level up",
"Reach out",
"Touch base",
"Is this in our Wheelhouse?",
"This is in our Wheelhouse!",
"Can we do that even if it's not in our Wheelhouse",
"Disruptor",
"Alignment",
"what is the Bottom line?",
"can we get to the Bottom line?",
"ROI",
"Disruptive",
"Value-add",
"Driving value",
"Value proposition",
"Corporate values",
"Value drop",
"Ping",
"Lean-in",
"Paradigm shift",
"Paradigm break",
"Partner with us",
"Business partner",
"Did you put in a change?",
"That's going to need a change request",
"I think that we need to review this in the managers meeting",
"We need to take a holistic approach",
"Creating a team culture",
"Thought leader",
"Content is king",
"Red and Blue teaming",
"Buy-in",
"Pain point",
"We need to stay in our own lanes",
"Best in class",
"Best of breed",
"Game-changer",
"Teamwork",
"Team-building",
"Team-players",
"Next-gen team",
"Next-gen telecommunication",
"Next-gen communication",
"Next-gen Next-gen",
"Next-gen best practices",
"Hard stop",
"ROI",
"Return on investment",
"IoT",
"Internet of things",
"Innovative",
"Influencer",
"Single pane of glass",
"Customer-centric",
"All hands on deck",
"Put a pin in it",
"Stakeholders",
"Board members",
"Strategic",
"Metrics",
"Machine Learning",
"Em Al",
"Pivot",
"On the same page",
"Advertainment",
"Collaboration",
"artificial intelligence",
"business intelligence",
"emotional intelligence",
"market intelligence",
"competitive intelligence",
"Automation",
"Blockchain",
"Intuitive",
"Analytics",
"Platform",
"Unpack",
"Giving 110%",
"table steaks",
"meow meow",
"bringing something to the table",
"tabling it for later",
"Quick win",
"Onboarding",
"get everyone on board",
"Scrum",
"Boil the ocean",
"storytelling"
"long story short",
"Do you have a full plate?",
"Just add this to your plate",
"Can you take care of this?",
"I need this yesterday.",
"is Windows finished?",
"when are we going to be done with all of the vulnerabilities?",
"30,000 ft. view",
"10,000 ft. view",
"top-down view",
"Core competency"
"Core capabilities",
"Rockstar",
"meow meow",
"Trail blazing",
"We'll rebuild that bridge if we need to.  So go ahead and burn it",
"Is it on the roadmap?",
"What is the upgrade Paradigm?"
"Let's loop back",
"keeping everyone in the loop",
"we'll need a foreach in the feedback loop",
"Can we find a freemium version?",
"Let's paint the town red",
"Integration",
"Engagement",
"Actionable",
"Efficiency",
"Socialize",
"Diversity",
"Verticals",
"Bio-break",
"Bleeding edge",
"meow meow",
"Optimize",
"Scalable",
"Time-bound",
"Measurable",
"Is this coffee organic?",
"Can this be written in nonGMO python?",
"Omni-channel",
"Empower",
"Win-win",
"Optics",
"DevOps",
"Data-driven",
"In the weeds",
"On your radar",
"Ducks in a row",
"Drill down",
"fast-paced",
"fail fast",
"Top of mind",
"We need to be mindful",
"Key performance indicator",
"ASAP",
"Relevant",
"Can we break that down?",
"Can we use a reverse split tunnel proxy?",
"We need to run this by governance",
"Can we do this ourselves and not use professional services? since you know you are all... professionals?",
"Let's be reasonable",
"can you just do the codes?",
"How hard could it be?",
"Can you check reddit?",
"Can you run that by r/sysadmin?",
"Have you checked on infosec?",
"we need to draft a communication",
"this is just first draft",
"Can we review the EULA?",
"We'll need that in writting",
"Can't we just build a thick image?",
"Can we look for an free openSource version?",
"I Believe You Have My Stapler.",
"Uh Oh. Sounds Like Somebody’s Got A Case Of The Mondays.",
"Oh, And Remember, Next Friday Is Hawaiian Shirt Day!",
"I Can't Believe What A Bunch Of Nerds We Are. We're Looking Up Money Laundering In A Dictionary.",
"Human Beings Were Not Meant To Sit In Little Cubicles Staring At Computer Screens All Day, Filling Out Useless Forms And Listening To Eight Different Bosses Drone On About Mission Statements!",
"I'm Going To Need Those TPS Reports ASAP. So, If You Could Do That, That'd Be Great...",
"Can this use MF-OATH?",
"It's Friday! It's two days until Monday.",
"we'll talk to over on an OOO, that's One-on-One.",
"I’m so honored, much appreciate, such blessing, WOW",
"have you checked your metadata?",
"have you checked your metadata",
"I know its out of scope, but can you do it anyways?",
"Can you do it anyways?",
"Can you just do it?",
"Giving back your time")

$bws | get-random }
